// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVV9KFcd37tti3kcMG-Be3cwbwL4QdUNk',
    appId: '1:62222013229:web:74004703d216cb86c939a4',
    messagingSenderId: '62222013229',
    projectId: 'expense-tracker-44f23',
    authDomain: 'expense-tracker-44f23.firebaseapp.com',
    storageBucket: 'expense-tracker-44f23.appspot.com',
    measurementId: 'G-PSPZWK0R6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQGWRjvVJtOeAK005Fh5ZCMqSY0mp6880',
    appId: '1:62222013229:android:a60a97ee5f80675ec939a4',
    messagingSenderId: '62222013229',
    projectId: 'expense-tracker-44f23',
    storageBucket: 'expense-tracker-44f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqDr4MXDsQwlf_NMtLMbyDBpB9aJnTsM',
    appId: '1:62222013229:ios:0ec89e2129f4266ac939a4',
    messagingSenderId: '62222013229',
    projectId: 'expense-tracker-44f23',
    storageBucket: 'expense-tracker-44f23.appspot.com',
    iosBundleId: 'com.cipherschools.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUqDr4MXDsQwlf_NMtLMbyDBpB9aJnTsM',
    appId: '1:62222013229:ios:7438577355d0774ac939a4',
    messagingSenderId: '62222013229',
    projectId: 'expense-tracker-44f23',
    storageBucket: 'expense-tracker-44f23.appspot.com',
    iosBundleId: 'com.cipherschools.assignment.RunnerTests',
  );
}
